version: "2"        // which version of compose syntax you are using
services:
  app:
    container_name: app
    build: .             // a self defined Dockerfile, see below
    ports:               // exposes port
    - "2375"         to other containers, and to our local
    volumes:             // maps so changes to these can be seen
    - ./Tests:/Tests
    - ./package.json:/package.json
    - ./package-lock.json:/package-lock.json
    - ./.gitignore:/.gitignore
    - ./app.js:/app.js